name: EventPlugin
version: 1.0
main: com.liincoding.eventplugin.EventPlugin
api-version: 1.21
commands:
  event:
    description: Event management commands
    usage: /<command> <start|join|leave> [eventName]
permissions:
  event.start:
    description: Allows starting events
    default: op
  event.join:
    description: Allows joining events
    default: true
  event.leave:
    description: Allows leaving events
    default: true