name: EventPlugin
version: 1.0
main: com.liincoding.eventplugin.EventPlugin
api-version: 1.21

commands:
  event:
    description: Start/join/leave/end events
    usage: /<command>

permissions:
  event.start:
    description: Allows starting events
    default: op
  event.join:
    description: Allows joining events
    default: true
  event.leave:
    description: Allows leaving events
    default: true
  event.admin:
    description: Allows ending events
    default: op
